In [1]:
import os
os.environ['http_proxy'] = "http://192.41.170.23:3128" 
os.environ['https_proxy'] = "http://192.41.170.23:3128" 

# export http_proxy=http://192.41.170.23:3128
# export https_proxy=http://192.41.170.23:3128

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
import torch

In [12]:
print("Is cuda available?", torch.cuda.is_available())
# !nvidia-smi

Is cuda available? True


## 00. PyTorch Fundamentals

In [15]:
print(torch.__version__)

2.0.0+cu117


## Introduction to Tensors

### Creating tensors

Pytorch tensors are craeted using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [18]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [19]:
scalar.ndim

0

In [22]:
# Get tensor back as Python int
scalar.item()

7

In [26]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [27]:
vector.ndim

1

In [28]:
vector.shape

torch.Size([2])

In [29]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [30]:
MATRIX.ndim

2

In [36]:
MATRIX[1]

tensor([ 9, 10])

In [37]:
MATRIX.shape

torch.Size([2, 2])

In [67]:
# TENSOR
TENSOR = torch.tensor([[[1,2],
                        [3,6],
                        [2,4],
                        [5,1],
                        [3,4]]])
TENSOR

tensor([[[1, 2],
         [3, 6],
         [2, 4],
         [5, 1],
         [3, 4]]])

In [68]:
TENSOR.ndim

3

In [69]:
TENSOR.shape

torch.Size([1, 5, 2])

In [70]:
TENSOR[0]

tensor([[1, 2],
        [3, 6],
        [2, 4],
        [5, 1],
        [3, 4]])

### Random tensors

Why random tensors?

Random tensors are important because the way many nerual networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [80]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1162, 0.2684, 0.2864, 0.5678],
        [0.1267, 0.1307, 0.0152, 0.7556],
        [0.3047, 0.5696, 0.1587, 0.2690]])

In [81]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [87]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [90]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [92]:
ones.dtype

torch.float32

In [93]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [101]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [118]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # what datatype is the tensor (e.g. float32, float16)
                                device=None, # What device is your tensor on 
                                requires_grad=False) # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [119]:
float_32_tensor.dtype

torch.float32

In [115]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [116]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [120]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [124]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [125]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from tensor, use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, use `tensor.device`

In [126]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4634, 0.0440, 0.8924, 0.8980],
        [0.2296, 0.9528, 0.8127, 0.0446],
        [0.2259, 0.1004, 0.2010, 0.1034]])

In [129]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4634, 0.0440, 0.8924, 0.8980],
        [0.2296, 0.9528, 0.8127, 0.0446],
        [0.2259, 0.1004, 0.2010, 0.1034]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [138]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [139]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [140]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [145]:
# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


In [143]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
  
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2,3 )` -> `(3, 3)`

In [160]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [147]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [148]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [149]:
tensor

tensor([1, 2, 3])

In [150]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [152]:
%%time
value = 0 
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  
print(value)

tensor(14)
CPU times: user 377 µs, sys: 167 µs, total: 544 µs
Wall time: 723 µs


In [153]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 37.4 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [161]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm = torch.matmul = @

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [162]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [166]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [167]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [172]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [186]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [187]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [188]:
# Find the min
torch.max(x), x.max()

(tensor(91), tensor(91))

In [189]:
# Find the mean - note the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [190]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [191]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [192]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [195]:
# Find the position in tensor that has the minimum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimension permuted (swapped) in a certain way

In [213]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [214]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [215]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [216]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [219]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [229]:
# torch.squeeze() = removes all single dimensions from a target tensors
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor shape: torch.Size([9])


In [233]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim 
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew target: {x_unsqueezed}")
print(f"New target shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New target shape: torch.Size([1, 9])


In [236]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors) 

Indexing with PyTorch is similar to indexing with NumPy

In [239]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [240]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [242]:
# Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [245]:
# Let's index on the most inner bracket (last dimension)
x[0, 2, 2]

tensor(9)

In [246]:
# You can also use ':' to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [247]:
# Get all values of the 0th and 1st deimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [248]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [249]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [255]:
# Index on x to return 9
print(x[0,2,2])

# Index of x to return 3, 6, 9 
x[:, :, 2]

tensor(9)


tensor([[3, 6, 9]])

# PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library. 

PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [263]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch reflects numpy's default dtype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [265]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [266]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [267]:
# Change the tensor, what happens to `numpy` tensor?
tensor = tensor + 1
tensor, numpy_tensor 

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [282]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4) 
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7517, 0.8892, 0.2351, 0.0933],
        [0.5382, 0.1615, 0.2184, 0.2742],
        [0.2024, 0.8814, 0.0906, 0.7065]])
tensor([[0.5749, 0.4414, 0.7201, 0.9755],
        [0.3712, 0.4646, 0.7341, 0.4726],
        [0.5614, 0.6795, 0.0382, 0.0940]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [299]:
# Let's mae some random but reproducible tensors
# Set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working good together

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and acces them

In [300]:
!nvidia-smi

Wed May 31 17:54:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:01:00.0 Off |                  Off |
| 67%   85C    P2   295W / 300W |  45185MiB / 49140MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:05:00.0 Off |                  N/A |
|  0%   

### 2. Check for GPU access with PyTorch

In [302]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

PyTorch can run on GPU or CPU, set up device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

In [304]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [305]:
# Count numbers of devices
torch.cuda.device_count()

2

## 3. Putting tensors and models on the GPU

The reason we want our tensors/models in the GPU is beacuse using a GPU results in faster computations.

In [306]:
# Create a tensor (default is on the CPU)
tensor = torch.tensor([1, 2, 3], device='cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [307]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [311]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [309]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [310]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises and Extra-cirruculum

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [322]:
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])

In [323]:
torch.matmul(random_tensor, torch.rand(1, 7).T)

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

In [324]:
torch.manual_seed(0)
                  
random_tensor = torch.rand(7, 7)
torch.matmul(random_tensor, torch.rand(1, 7).T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [327]:
torch.cuda.manual_seed(1234)

In [330]:
torch.manual_seed(1234)

a = torch.rand(2, 3).to(device)
b = torch.rand(2, 3).to(device)

In [333]:
c = a @ b.T
c

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [336]:
c.max(), c.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [337]:
c.argmax(), c.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [341]:
torch.manual_seed(7)

d = torch.rand(1, 1, 1, 10)

print(d, d.shape)

print(d.squeeze(), d.squeeze().shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
